---
name: Build

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install Prettier
        run: npm install --global prettier

      - name: Run Prettier
        run: prettier --check README.md

      - name: Run dockerfmt on Dockerfile
        run: |
          docker run --rm -i ghcr.io/reteps/dockerfmt:latest -c <Dockerfile

      - name: Run hadolint on Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: crisis-tools:latest
